(function (root) {
  "use strict";
  const GOLDEN = Math.PI * (3 - Math.sqrt(5));
  function hash(text) { let h = 2166136261; for (const ch of String(text)) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; }
  function sphere(i, total, radius, center) { const y = 1 - 2 * (i + .5) / Math.max(1, total), r = Math.sqrt(Math.max(0, 1 - y * y)), a = GOLDEN * i, c = center || { x: 0, y: 0, z: 0 }; return { x: c.x + Math.cos(a) * r * radius, y: c.y + y * radius, z: c.z + Math.sin(a) * r * radius }; }
  function traverse(start, nodeMap, key) { const seen = new Set(), queue = [start]; for (let i = 0; i < queue.length; i += 1) { const id = queue[i]; if (seen.has(id)) continue; seen.add(id); const node = nodeMap.get(id); if (node) (node[key] || []).forEach(next => { if (!seen.has(next)) queue.push(next); }); } return seen; }
  function pageRank(nodes) { const count = Math.max(1, nodes.length), damping = .85; let rank = new Map(nodes.map(n => [n.id, 1 / count])); for (let step = 0; step < 24; step += 1) { const next = new Map(nodes.map(n => [n.id, (1 - damping) / count])); let dangling = 0; nodes.forEach(n => { if (!n.toIds.length) dangling += rank.get(n.id) || 0; else n.toIds.forEach(id => next.set(id, (next.get(id) || 0) + damping * (rank.get(n.id) || 0) / n.toIds.length)); }); const share = damping * dangling / count; nodes.forEach(n => next.set(n.id, next.get(n.id) + share)); rank = next; } return rank; }
  function enrich(graph) {
    graph.nodes.forEach(n => { n.id = String(n.id); }); const nodeMap = new Map(graph.nodes.map(n => [n.id, n]));
    graph.nodes.forEach((n, i) => { const p = sphere(i, graph.nodes.length, Math.max(210, Math.sqrt(graph.nodes.length) * 42)); Object.assign(n, p, { homeX: p.x, homeY: p.y, homeZ: p.z, vx: 0, vy: 0, vz: 0, toIds: [], fromIds: [], neighborIds: [], depth: 0 }); });
    graph.edges = graph.edges.filter(e => nodeMap.has(String(e.source)) && nodeMap.has(String(e.target))).map((e, i) => Object.assign(e, { id: e.id || `e${i + 1}`, source: String(e.source), target: String(e.target), a: nodeMap.get(String(e.source)), b: nodeMap.get(String(e.target)), weight: Number.isFinite(Number(e.weight)) ? Number(e.weight) : 1 }));
    graph.edges.forEach(e => { e.a.neighborIds.push(e.b.id); e.b.neighborIds.push(e.a.id); e.a.toIds.push(e.b.id); e.b.fromIds.push(e.a.id); if (!e.directed) { e.b.toIds.push(e.a.id); e.a.fromIds.push(e.b.id); } });
    graph.nodes.forEach(n => { n.neighborIds = Array.from(new Set(n.neighborIds)); n.toIds = Array.from(new Set(n.toIds)); n.fromIds = Array.from(new Set(n.fromIds)); });
    const roots = graph.nodes.filter(n => !n.fromIds.length), queue = roots.map(n => n.id), depths = new Map(queue.map(id => [id, 0])); for (let i = 0; i < queue.length; i += 1) { const n = nodeMap.get(queue[i]), d = depths.get(n.id); n.toIds.forEach(id => { const nd = Math.min(8, d + 1); if (!depths.has(id) || depths.get(id) > nd) { depths.set(id, nd); queue.push(id); } }); } graph.nodes.forEach(n => { n.depth = depths.has(n.id) ? depths.get(n.id) : Math.min(4, n.fromIds.length ? 2 : 0); });
    const ranks = pageRank(graph.nodes), denom = Math.max(1, graph.nodes.length - 1);
    graph.nodes.forEach(n => { const down = traverse(n.id, nodeMap, "toIds"), up = traverse(n.id, nodeMap, "fromIds"); down.delete(n.id); up.delete(n.id); n.degree = n.neighborIds.length; n.rank = ranks.get(n.id) || 0; n.metrics = { degree: n.degree / denom, pagerank: n.rank, reachability: (down.size + up.size) / (2 * denom), descendants: down.size / denom, prerequisites: up.size / denom }; n.descendantCount = down.size; n.ancestorCount = up.size; });
    const metricRanges = {}; ["degree", "pagerank", "reachability", "descendants", "prerequisites"].forEach(key => { const values = graph.nodes.map(n => n.metrics[key]); metricRanges[key] = [Math.min(...values), Math.max(...values)]; });
    return Object.assign(graph, { nodeMap, metricRanges, getUpstream(id) { return traverse(id, nodeMap, "fromIds"); }, getDownstream(id) { return traverse(id, nodeMap, "toIds"); }, getNeighborhood(id) { const n = nodeMap.get(id); return new Set([id].concat(n ? n.neighborIds : [])); } });
  }
  function grouped(nodes, key) { const map = new Map(); nodes.forEach(n => { const raw = key(n), value = String(raw == null || raw === "" ? "unassigned" : raw); if (!map.has(value)) map.set(value, []); map.get(value).push(n); }); return map; }
  function clusterTargets(nodes, key) { const groups = grouped(nodes, n => key === "category" ? n.category : n.properties && n.properties[key]), entries = Array.from(groups.entries()).sort((a, b) => a[0].localeCompare(b[0])), out = new Map(); entries.forEach(([_, list], i) => { const c = sphere(i, entries.length, Math.max(260, entries.length * 36)); list.sort((a, b) => a.label.localeCompare(b.label)).forEach((n, j) => out.set(n.id, sphere(j, list.length, Math.max(42, Math.sqrt(list.length) * 28), c))); }); return out; }
  function semanticTargets(nodes, key) { const groups = grouped(nodes, n => key === "category" ? n.category : n.properties && n.properties[key]), entries = Array.from(groups.entries()).sort((a, b) => a[0].localeCompare(b[0])), out = new Map(); entries.forEach(([_, list], i) => { const angle = i / Math.max(1, entries.length) * Math.PI * 2, c = { x: Math.cos(angle) * 380, y: (i % 3 - 1) * 90, z: Math.sin(angle) * 380 }; list.sort((a, b) => b.rank - a.rank).forEach((n, j) => out.set(n.id, sphere(j, list.length, Math.max(48, Math.sqrt(list.length) * 31), c))); }); return out; }
  function hierarchicalTargets(nodes) {
    const groups = grouped(nodes, n => n.depth), depths = Array.from(groups.keys()).map(Number).sort((a, b) => a - b), out = new Map();
    depths.forEach((depth, di) => {
      const list = groups.get(String(depth)), y = (di - (depths.length - 1) / 2) * 150, radius = Math.max(90, list.length * 5.4);
      list.sort((a, b) => a.category.localeCompare(b.category) || a.label.localeCompare(b.label)).forEach((n, i) => out.set(n.id, { x: Math.cos(i / list.length * Math.PI * 2) * radius, y, z: Math.sin(i / list.length * Math.PI * 2) * radius }));
    });
    return out;
  }
  function radialTargets(graph, centerId) { const distance = new Map([[centerId, 0]]), queue = [centerId]; for (let i = 0; i < queue.length; i += 1) { const n = graph.nodeMap.get(queue[i]); if (n) n.neighborIds.forEach(id => { if (!distance.has(id)) { distance.set(id, distance.get(n.id) + 1); queue.push(id); } }); } const shells = grouped(graph.nodes, n => distance.has(n.id) ? distance.get(n.id) : 99), out = new Map([[centerId, { x: 0, y: 0, z: 0 }]]); shells.forEach((list, key) => { const d = Number(key); if (!d) return; const radius = d === 99 ? 680 : Math.min(580, d * 110); list.sort((a, b) => a.label.localeCompare(b.label)).forEach((n, i) => out.set(n.id, sphere(i, list.length, radius))); }); return out; }
  function homeTargets(nodes) { return new Map(nodes.map(n => [n.id, { x: n.homeX, y: n.homeY, z: n.homeZ }])); }
  function forceStep(graph, options) { const nodes = graph.nodes, edges = graph.edges, repulsion = 800 + 3100 * options.repulsion, damping = .84 + .1 * (1 - options.repulsion), collision = 10 + 24 * options.collision; if (nodes.length <= 460) for (let i = 0; i < nodes.length; i += 1) for (let j = i + 1; j < nodes.length; j += 1) { const a = nodes[i], b = nodes[j], dx = a.x - b.x, dy = a.y - b.y, dz = a.z - b.z, d2 = dx * dx + dy * dy + dz * dz + 12, d = Math.sqrt(d2), f = repulsion / d2 + (d < collision ? (collision - d) * .05 : 0); a.vx += dx / d * f; a.vy += dy / d * f; a.vz += dz / d * f; b.vx -= dx / d * f; b.vy -= dy / d * f; b.vz -= dz / d * f; }
    edges.forEach(e => { const dx = e.b.x - e.a.x, dy = e.b.y - e.a.y, dz = e.b.z - e.a.z, d = Math.sqrt(dx * dx + dy * dy + dz * dz) || 1, relation = options.relations.get(e.type) ?? options.extra, strength = .0008 + relation * .0042, desired = 88 + (1 - relation) * 80, f = (d - desired) * strength * (.5 + .5 * Math.max(.1, e.forceWeight || e.weight)); e.a.vx += dx / d * f; e.a.vy += dy / d * f; e.a.vz += dz / d * f; e.b.vx -= dx / d * f; e.b.vy -= dy / d * f; e.b.vz -= dz / d * f; });
    nodes.forEach(n => { const anchor = options.anchors.get(n.category || "node"); if (anchor) { n.vx += (anchor.x - n.x) * options.anchor * .00065; n.vy += (anchor.y - n.y) * options.anchor * .00065; n.vz += (anchor.z - n.z) * options.anchor * .00065; } n.vx *= damping; n.vy *= damping; n.vz *= damping; n.x += n.vx; n.y += n.vy; n.z += n.vz; }); }
  function applyTargets(nodes, targets, immediate) { nodes.forEach(n => { const p = targets.get(n.id); if (!p) return; if (immediate) Object.assign(n, p); else n.layoutTarget = p; n.vx = n.vy = n.vz = 0; }); }
  function transitionStep(nodes, amount) { let moving = false; nodes.forEach(n => { if (!n.layoutTarget) return; const p = n.layoutTarget; n.x += (p.x - n.x) * amount; n.y += (p.y - n.y) * amount; n.z += (p.z - n.z) * amount; if (Math.abs(p.x - n.x) + Math.abs(p.y - n.y) + Math.abs(p.z - n.z) < .5) { Object.assign(n, p); n.layoutTarget = null; } else moving = true; }); return moving; }
  function components(graph, filter) { const parent = new Map(graph.nodes.map(n => [n.id, n.id])); function find(x) { while (parent.get(x) !== x) x = parent.get(x); return x; } function join(a, b) { a = find(a); b = find(b); if (a !== b) parent.set(b, a); } const edges = graph.edges.filter(filter || (() => true)); edges.forEach(e => join(e.source, e.target)); const roots = new Set(graph.nodes.map(n => find(n.id))); return { groups: Array.from(roots), beta0: roots.size, beta1: Math.max(0, edges.length - graph.nodes.length + roots.size), edges: edges.length }; }
  const api = { hash, sphere, enrich, clusterTargets, semanticTargets, hierarchicalTargets, radialTargets, homeTargets, forceStep, applyTargets, transitionStep, components };
  root.CSVGraphModel = api; if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
