(function () {
  "use strict";
  const Core = CSVGraphCore, Model = CSVGraphModel, Topology = CSVGraphTopology;
  const STORAGE_KEY = "universal.constellation.graph.v2", META_KEY = "universal.constellation.meta.v2";
  const SNAPSHOT_DB = "universal.constellation.storage.v1", SNAPSHOT_STORE = "snapshots", ACTIVE_SNAPSHOT = "active";
  const palette = ["#7aa2f7", "#64d8cb", "#b58cff", "#ff9f68", "#ff7eb6", "#a4ef9b", "#ffd36e", "#72e5ff", "#f08c8c", "#87c7ff", "#d2a8ff", "#7ce8a6"];
  const $ = id => document.getElementById(id), canvas = $("space"), ctx = canvas.getContext("2d"), orientation = $("orientation"), octx = orientation.getContext("2d");
  let graph, schema, meta, anchors = new Map(), searchMatches = new Set(), activeContext = new Set(), localNodes = new Set(), topologyResult = null;
  const state = { w: 1, h: 1, pixel: devicePixelRatio || 1, dist: 760, targetDist: 760, zoom: 1, targetZoom: 1, rx: -.55, ry: .62, spread: 1, labels: true, labelDensity: .48, mode: "3d", layout: "force", selectedIds: new Set(), showSources: true, showOutcomes: false, autoRotate: false, colorMode: "category", sizeMode: "structural", clusterMode: "category", weightMode: "strength", panX: 0, panY: 0, focusX: 0, focusY: 0, focusZ: 0, targetFocusX: 0, targetFocusY: 0, targetFocusZ: 0, local: false, selected: null, hovered: null, drag: null, moved: false, suppressClick: false, lastX: 0, lastY: 0, physics: true, transitioning: false, categoryFilters: new Map(), edgeTypes: new Set(), relationGravity: new Map(), force: { extra: .46, anchor: .38, repulsion: .54, collision: .72 }, tda: false, areaFill: false, epsilon: .52 };

  function safe(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, ch => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch])); }
  function safeURL(value) { if(!value)return ""; try { const u=new URL(value,location.href); return ["http:","https:"].includes(u.protocol)?u.href:""; } catch { return ""; } }
  function number(value, fallback) { const n = Number(value); return Number.isFinite(n) ? n : fallback; }
  function colorKey(value) { return palette[Model.hash(String(value || "unassigned")) % palette.length]; }
  function valueFor(node, key) { if (key === "category") return node.category; if (node.metrics && key in node.metrics) return node.metrics[key]; return node.properties ? node.properties[key] : ""; }
  function stripNode(n) { return Object.fromEntries(Object.entries(n).filter(([k])=>!["x","y","z","vx","vy","vz","homeX","homeY","homeZ","toIds","fromIds","neighborIds","depth","upstream","downstream","degree","rank","metrics","descendantCount","ancestorCount","_p","_radius","_dragging","layoutTarget"].includes(k))); }
  function stripEdge(e) { return Object.fromEntries(Object.entries(e).filter(([k])=>!["a","b","type","filterWeight","forceWeight"].includes(k))); }
  function snapshot() { return {format:"ml-knowledge-graph/csv-v1",nodes:graph.nodes.map(stripNode),edges:graph.edges.map(stripEdge),importMeta:meta}; }
  function download(name, text, type) { const blob = new Blob([text], { type: type || "application/json" }), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function parseBundled() { return Core.normalizeTables([Core.inferTable("science_world_nodes.csv", Core.parseCSV(CSVGraphSample.nodesCSV)), Core.inferTable("science_world_edges.csv", Core.parseCSV(CSVGraphSample.edgesCSV))]); }
  function openSnapshotDB() { return new Promise((resolve, reject) => { if (!window.indexedDB) { reject(new Error("IndexedDB is unavailable in this browser.")); return; } const request = indexedDB.open(SNAPSHOT_DB, 1); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(SNAPSHOT_STORE)) db.createObjectStore(SNAPSHOT_STORE); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error || new Error("The snapshot database could not be opened.")); request.onblocked = () => reject(new Error("The snapshot database is blocked by another open tab.")); }); }
  async function readDatabaseSnapshot() { const db = await openSnapshotDB(); return new Promise((resolve, reject) => { const tx = db.transaction(SNAPSHOT_STORE, "readonly"), request = tx.objectStore(SNAPSHOT_STORE).get(ACTIVE_SNAPSHOT); request.onsuccess = () => resolve(request.result || null); request.onerror = () => reject(request.error || new Error("The saved snapshot could not be read.")); tx.oncomplete = () => db.close(); tx.onabort = tx.onerror = () => { db.close(); reject(tx.error || new Error("The saved snapshot could not be read.")); }; }); }
  async function writeDatabaseSnapshot(raw, savedMeta) { const db = await openSnapshotDB(); return new Promise((resolve, reject) => { const tx = db.transaction(SNAPSHOT_STORE, "readwrite"); tx.objectStore(SNAPSHOT_STORE).put({ raw, meta: savedMeta, savedAt: Date.now() }, ACTIVE_SNAPSHOT); tx.oncomplete = () => { db.close(); resolve(); }; tx.onabort = tx.onerror = () => { db.close(); reject(tx.error || new Error("The snapshot database rejected the write.")); }; }); }
  async function deleteDatabaseSnapshot() { try { const db = await openSnapshotDB(); await new Promise((resolve, reject) => { const tx = db.transaction(SNAPSHOT_STORE, "readwrite"); tx.objectStore(SNAPSHOT_STORE).delete(ACTIVE_SNAPSHOT); tx.oncomplete = resolve; tx.onabort = tx.onerror = () => reject(tx.error || new Error("The saved snapshot could not be removed.")); }); db.close(); } catch (_) {} }
  async function saveBrowserSnapshot(raw, savedMeta) { try { await writeDatabaseSnapshot(raw, savedMeta); localStorage.removeItem(STORAGE_KEY); localStorage.removeItem(META_KEY); return; } catch (databaseError) { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(raw)); localStorage.setItem(META_KEY, JSON.stringify(savedMeta)); return; } catch (localError) { throw new Error(`Browser storage is unavailable or full. IndexedDB: ${databaseError.message} Local fallback: ${localError.message}`); } } }
  async function resolveSnapshot() { if (window.__CSV_GRAPH_OVERRIDE__?.nodes) return { raw: window.__CSV_GRAPH_OVERRIDE__, meta: { source: "embedded override" } }; try { const saved = await readDatabaseSnapshot(); if (saved?.raw?.nodes?.length) return { raw: saved.raw, meta: saved.meta || { source: "saved browser snapshot" } }; } catch (_) {} try { const raw = JSON.parse(localStorage.getItem(STORAGE_KEY)), savedMeta = JSON.parse(localStorage.getItem(META_KEY)); if (raw?.nodes?.length) return { raw, meta: savedMeta || { source: "saved browser snapshot" } }; } catch (_) {} return { raw: parseBundled(), meta: { source: "bundled science sample", filenames: ["science_world_nodes.csv", "science_world_edges.csv"] } }; }

  function initialize(raw, importMeta) {
    graph = Model.enrich({ nodes: raw.nodes.map(n => Object.assign({}, n, { properties: Object.assign({}, n.properties) })), edges: raw.edges.map(e => Object.assign({}, e, { properties: Object.assign({}, e.properties) })), warnings: raw.warnings || [] });
    schema = Core.inferDisplaySchema(graph); meta = importMeta || {}; state.selectedIds.clear(); state.selected = state.hovered = null; state.categoryFilters.clear(); state.edgeTypes = new Set(schema.edgeTypes); state.relationGravity.clear(); schema.edgeTypes.forEach(type => state.relationGravity.set(type, .6));
    state.colorMode = "category"; state.sizeMode = "structural"; state.clusterMode = schema.categorical[0]?.key || "category"; prepareWeights(); buildAnchors(); buildControls(); refreshContext(); recomputeTDA(); setInspect(null); updateStats(); updateProvenance();
    const initial = readHash(); if (initial && graph.nodeMap.has(initial)) selectNode(graph.nodeMap.get(initial), false);
  }
  function prepareWeights() {
    const field=$("weightField")?.value||"weight";
    const values=api('/api/graph/weights',{edges:graph.edges.map(cleanEdge),field,mode:state.weightMode});
    values.forEach((e,i)=>{graph.edges[i].filterWeight=e.filterWeight;graph.edges[i].forceWeight=e.forceWeight;});
  }
  function buildAnchors() { anchors=new Map(Object.entries(api('/api/graph/anchors',{nodes:graph.nodes.map(cleanNode)}))); }
  function metricNorm(node, key) { const range = graph.metricRanges[key] || [0, 1], span = range[1] - range[0]; return span ? Math.max(0, Math.min(1, (node.metrics[key] - range[0]) / span)) : 0; }
  function colorFor(node) { if (state.colorMode === "custom" && node.color) return node.color; if (node.metrics && state.colorMode in node.metrics) { const t = metricNorm(node, state.colorMode); return `hsl(${218 - t * 194} 82% ${48 + t * 18}%)`; } const numeric = schema.numeric.find(x => x.key === state.colorMode); if (numeric) { const t = (number(valueFor(node, numeric.key), numeric.min) - numeric.min) / Math.max(1e-9, numeric.max - numeric.min); return `hsl(${218 - t * 194} 82% ${48 + t * 18}%)`; } return colorKey(valueFor(node, state.colorMode) || node.category); }
  function radiusFor(node) { if (state.sizeMode === "structural") return 4.1 + Math.min(4.5, Math.sqrt(node.degree) * .65) + (node.category === "discipline" ? 2.2 : 0); if (node.metrics && state.sizeMode in node.metrics) return 3.5 + metricNorm(node, state.sizeMode) * 8; const numeric = schema.numeric.find(x => x.key === state.sizeMode); if (numeric) return 3.5 + Math.max(0, Math.min(1, (number(valueFor(node, numeric.key), numeric.min) - numeric.min) / Math.max(1e-9, numeric.max - numeric.min))) * 8; return 5; }
  function searchable(node) { return [node.id, node.label, node.category].concat(Object.values(node.properties || {})).join(" ").toLowerCase(); }
  function passesFilters(node) { for (const [key, allowed] of state.categoryFilters) if (!allowed.has(String(valueFor(node, key) || "unassigned"))) return false; return true; }
  function visible(node) { return passesFilters(node) && (!state.local || !state.selectedIds.size || localNodes.has(node.id)); }
  function edgeEnabled(edge) { return state.edgeTypes.has(edge.type); }
  function eligibleEdges() { return graph.edges.filter(e => edgeEnabled(e) && visible(e.a) && visible(e.b)); }

  function buildControls() { buildSelectors(); buildCategoryFilters(); buildRelationFilters(); buildGravity(); buildLegend(); }
  function fillSelect(select, values, current) { const seen = new Set(); select.innerHTML = values.filter(x => { const key = x.key || x; if (seen.has(key)) return false; seen.add(key); return true; }).map(x => `<option value="${safe(x.key || x)}">${safe(x.label || x.key || x)}</option>`).join(""); if (Array.from(select.options).some(o => o.value === current)) select.value = current; }
  function buildSelectors() { fillSelect($("colorMode"), [{ key: "category" }, { key: "degree" }, { key: "pagerank", label: "PageRank" }, { key: "reachability" }].concat(schema.categorical.filter(x => x.key !== "category"), schema.numeric, graph.nodes.some(n => n.color) ? [{ key: "custom", label: "CSV color" }] : []), state.colorMode); fillSelect($("sizeMode"), [{ key: "structural" }, { key: "degree" }, { key: "pagerank", label: "PageRank" }, { key: "reachability" }].concat(schema.numeric), state.sizeMode); fillSelect($("clusterMode"), schema.categorical.length ? schema.categorical : [{ key: "category" }], state.clusterMode); }
  function buildCategoryFilters() { const box = $("categoryFilters"); box.innerHTML = "<div class='filter-head'><span>database layers</span></div>"; schema.categorical.slice(0, 6).forEach(field => { const values = field.values.map(String); state.categoryFilters.set(field.key, new Set(values)); const group = document.createElement("div"); group.className = "filter-group"; group.innerHTML = `<div class="filter-head"><span>${safe(field.key)}</span><button class="text-button">all</button></div><div class="filter-values">${values.map(v => `<label class="filter-chip"><input type="checkbox" checked value="${safe(v)}"><span class="swatch" style="color:${colorKey(v)};background:${colorKey(v)}"></span>${safe(v)} · ${graph.nodes.filter(n => String(valueFor(n, field.key) || "unassigned") === v).length}</label>`).join("")}</div>`; const inputs = group.querySelectorAll("input"), set = state.categoryFilters.get(field.key); inputs.forEach(input => input.onchange = () => { input.checked ? set.add(input.value) : set.delete(input.value); input.parentElement.classList.toggle("off", !input.checked); changedVisibility(); }); group.querySelector("button").onclick = () => { const all = Array.from(inputs).every(i => i.checked); inputs.forEach(input => { input.checked = !all; input.parentElement.classList.toggle("off", all); all ? set.delete(input.value) : set.add(input.value); }); changedVisibility(); }; box.appendChild(group); }); }
  function buildRelationFilters() { const counts = new Map(); graph.edges.forEach(e => counts.set(e.type, (counts.get(e.type) || 0) + 1)); const types = Array.from(counts).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])), box = $("relationFilters"); box.innerHTML = `<div class="filter-head"><span>relation families</span><button id="toggleRelations" class="text-button">all</button></div><div class="relation-list">${types.map(([type, count]) => `<label class="relation-row"><input type="checkbox" checked value="${safe(type)}"><span><i class="swatch" style="display:inline-block;color:${colorKey(type)};background:${colorKey(type)}"></i> ${safe(type)}</span><b>${count}</b></label>`).join("")}</div>`; const inputs = box.querySelectorAll("input"); inputs.forEach(input => input.onchange = () => { input.checked ? state.edgeTypes.add(input.value) : state.edgeTypes.delete(input.value); changedVisibility(); }); $("toggleRelations").onclick = () => { const all = Array.from(inputs).every(i => i.checked); state.edgeTypes.clear(); inputs.forEach(i => { i.checked = !all; if (!all) state.edgeTypes.add(i.value); }); changedVisibility(); }; }
  function buildGravity() { const counts = new Map(); graph.edges.forEach(e => counts.set(e.type, (counts.get(e.type) || 0) + 1)); const top = Array.from(counts).sort((a, b) => b[1] - a[1]).slice(0, 10), box = $("relationGravity"); box.innerHTML = top.map(([type]) => `<div class="force-row"><label title="${safe(type)}">${safe(type)}</label><input data-gravity="${safe(type)}" type="range" min="0" max="100" value="60"><output>60</output></div>`).join(""); box.querySelectorAll("input").forEach(input => input.oninput = () => { state.relationGravity.set(input.dataset.gravity, input.value / 100); input.nextElementSibling.value = input.value; resumePhysics(); }); }
  function buildLegend() { const field = schema.categorical.find(x => x.key === state.colorMode), box = $("legend"); if (field) box.innerHTML = field.values.slice(0, 30).map(v => `<div class="legend-row"><span class="swatch" style="color:${colorKey(v)};background:${colorKey(v)}"></span>${safe(v)}</div>`).join(""); else box.innerHTML = `<div class="note">${state.colorMode === "custom" ? "Colors are read from the node CSV." : "The selected analytic property uses a continuous blue-to-orange scale."}</div>`; }
  function changedVisibility() { refreshContext(); recomputeTDA(); updateStats(); }
  function resumePhysics() { state.physics = true; state.layout = "force"; $("layoutSelect").value = "force"; $("physicsToggle").textContent = "pause"; $("physicsToggle").classList.add("active"); }

  async function inspectFiles(fileList) {
    const files=Array.from(fileList).filter(f=>/\.csv$/i.test(f.name));
    if(!files.length){$("importStatus").textContent="Choose CSV files.";return;}
    await window.reviewCSV(files,async(raw,savedMeta)=>{await saveBrowserSnapshot(raw,savedMeta);location.reload();});
  }
  function refreshContext() { activeContext = new Set(state.selectedIds); localNodes = new Set(state.selectedIds); state.selectedIds.forEach(id => { const node = graph.nodeMap.get(id); node?.neighborIds.forEach(x => localNodes.add(x)); if (state.showSources) graph.getUpstream(id).forEach(x => activeContext.add(x)); if (state.showOutcomes) graph.getDownstream(id).forEach(x => activeContext.add(x)); }); }
  function selectNode(node, additive) { const next = additive ? new Set(state.selectedIds) : new Set(); if (node) { if (additive && next.has(node.id)) next.delete(node.id); else next.add(node.id); } state.selectedIds = next; state.selected = node && next.has(node.id) ? node : graph.nodeMap.get(Array.from(next).at(-1)) || null; refreshContext(); $("layoutSelect").querySelector('option[value="radial"]').disabled = next.size !== 1; if (state.selected) history.replaceState(null, "", `#node=${encodeURIComponent(state.selected.id)}`); else history.replaceState(null, "", location.pathname + location.search); setInspect(state.selected); recomputeTDA(); }
  function readHash() { const match = location.hash.match(/^#node=(.+)$/); if (!match) return null; try { return decodeURIComponent(match[1]); } catch (_) { return match[1]; } }
  function setInspect(node) { const box = $("inspect"); if (state.selectedIds.size > 1) { const selected = Array.from(state.selectedIds).map(id => graph.nodeMap.get(id)).filter(Boolean), outside = new Set(); selected.forEach(n => n.neighborIds.forEach(id => { if (!state.selectedIds.has(id)) outside.add(id); })); box.innerHTML = `<div class="node-title">${selected.length} selected nodes</div><div class="node-type">selection group</div><div class="quiet">Recursive context is computed from the union of all selected nodes.</div>${selected.map(n => `<span class="selection-chip">${safe(n.label)}</span>`).join("")}<div class="topology-block">external direct neighbors: <b>${outside.size}</b></div>`; return; } if (!node) { box.innerHTML = '<div class="note">Select any visible node to inspect its local constellation and imported properties.</div>'; return; }
    const neighbors = node.neighborIds.map(id => graph.nodeMap.get(id)).filter(Boolean), properties = Object.entries(node.properties || {}).filter(([_, v]) => String(v).trim()); let topo = ""; if (state.tda && topologyResult?.componentIndexByNode.has(node.id)) { const root = topologyResult.current.rootByNode.get(node.id), size = topologyResult.current.componentSizes.get(root) || 1, cycleDegree = topologyResult.edges.filter(e => e.filterWeight <= state.epsilon && topologyResult.current.cycleEdgeIds.has(e.id) && (e.a === node || e.b === node)).length; topo = `<div class="topology-block"><b>topological lens</b><br>filtration scale: ${state.epsilon.toFixed(2)}<br>component: C${topologyResult.componentIndexByNode.get(node.id)} · size ${size}<br>cycle-generating relations: ${cycleDegree}</div>`; }
    box.innerHTML = `<div class="node-title">${safe(node.label)}</div><div class="node-type">${safe(node.category)}</div><div class="stat"><b>relations:</b> ${neighbors.length}<br><b>ancestors:</b> ${node.ancestorCount} · <b>descendants:</b> ${node.descendantCount}<br><b>PageRank:</b> ${node.rank.toFixed(5)}</div>${safeURL(node.url) ? `<a class="open-source" href="${safe(safeURL(node.url))}" target="_blank" rel="noopener">open source link ↗</a>` : ""}${topo}<table class="property-table"><tbody>${properties.map(([k, v]) => `<tr><th>${safe(k)}</th><td>${safe(v)}</td></tr>`).join("")}</tbody></table><h3 style="margin-top:16px">neighbors</h3>${neighbors.map(n => `<div class="neighbor" data-id="${safe(n.id)}">${safe(n.label)}<span>${safe(n.category)}</span></div>`).join("") || '<div class="quiet">No direct neighbors.</div>'}`; box.querySelectorAll("[data-id]").forEach(el => el.onclick = () => selectNode(graph.nodeMap.get(el.dataset.id), false)); const evidence=document.createElement('details');evidence.id='relationEvidence';const title=document.createElement('summary');title.textContent='Relations and evidence';evidence.append(title);
    graph.edges.filter(e=>e.source===node.id||e.target===node.id).forEach(e=>{const pre=document.createElement('pre');pre.style.whiteSpace='pre-wrap';pre.textContent=JSON.stringify(stripEdge(e),null,2);evidence.append(pre);});box.append(evidence); }
  function updateStats() { const shown = graph.nodes.filter(visible), edges = eligibleEdges(), counts = new Map(); shown.forEach(n => counts.set(n.category, (counts.get(n.category) || 0) + 1)); $("topStats").textContent = `${shown.length} nodes · ${edges.length} relations`; $("stats").innerHTML = `visible nodes: <b>${shown.length}</b><br>visible relations: <b>${edges.length}</b><br>directed relations: <b>${edges.filter(e => e.directed).length}</b><br>categories: <b>${counts.size}</b>${state.tda ? `<br><span class="status-pill">topological lens active</span><br>components: <b>${topologyResult.beta0}</b> · cycles: <b>${topologyResult.beta1}</b>` : ""}`; }
  function updateProvenance() { $("importStatus").textContent = meta.importedAt ? `imported ${new Date(meta.importedAt).toLocaleString()} · ${meta.filenames?.join(" + ") || "CSV"}` : `${meta.source || "bundled snapshot"} · ${graph.nodes.length} nodes · ${graph.edges.length} relations`; $("provenance").innerHTML = `<b>source:</b> ${safe(meta.source || "bundled snapshot")}<br><b>files:</b> ${safe((meta.filenames || []).join(" + ") || "embedded sample")}<br><b>stored:</b> browser-local only${meta.importedAt ? `<br><b>imported:</b> ${safe(new Date(meta.importedAt).toLocaleString())}` : ""}${meta.warnings?.length ? `<br><b>warnings:</b> ${meta.warnings.length}` : ""}`; }

  function recomputeTDA() { const nodes = graph.nodes.filter(visible), ids = new Set(nodes.map(n => n.id)), edges = graph.edges.filter(e => edgeEnabled(e) && ids.has(e.a.id) && ids.has(e.b.id)); topologyResult = Topology.analyze(nodes, edges, state.epsilon, state.areaFill); $("tdaWrap").classList.toggle("off", !state.tda); $("tdaWrap").classList.toggle("faces-on", state.areaFill); drawTDAPlots(); updateStats(); if (state.selected) setInspect(state.selected); }
  function preparePlot(id, height) { const c = $(id), width = Math.max(210, c.clientWidth || 230), dpr = devicePixelRatio || 1; c.width = width * dpr; c.height = height * dpr; const x = c.getContext("2d"); x.setTransform(dpr, 0, 0, dpr, 0, 0); x.clearRect(0, 0, width, height); return { x, w: width, h: height }; }
  function drawTDAPlots() { if (!topologyResult) return; const r = topologyResult; $("tdaKpis").innerHTML = `<div class="tda-kpi"><b>${r.beta0}</b><span>β₀</span></div><div class="tda-kpi"><b>${r.beta1}</b><span>β₁</span></div><div class="tda-kpi"><b>${r.beta2}</b><span>β₂</span></div><div class="tda-kpi"><b>${r.euler}</b><span>χ</span></div>`; $("tdaSummary").innerHTML = `active relations: <b>${r.current.edgeCount}</b> · filled 2-cells: <b>${r.activeFaces.length}</b><br>largest component: <b>${r.largest}</b> · intervals H₀/H₁/H₂: <b>${r.h0.length}/${r.h1.length}/${r.h2.length}</b>`; drawBetti(r); drawBarcode(r); }
  function drawBetti(r) { const { x, w, h } = preparePlot("bettiPlot", 112), m = { l: 24, r: 9, t: 18, b: 17 }, pw = w - m.l - m.r, ph = h - m.t - m.b, max = Math.max(1, ...r.curves.map(d => Math.max(d.beta0, d.beta1, d.beta2))); x.strokeStyle = "rgba(255,255,255,.11)"; x.beginPath(); x.moveTo(m.l, m.t); x.lineTo(m.l, h - m.b); x.lineTo(w - m.r, h - m.b); x.stroke(); [["beta0", "#72e5ff"], ["beta1", "#ff6fcf"], ["beta2", "#a4ef9b"]].forEach(([key, color]) => { if (key === "beta2" && !state.areaFill) return; x.strokeStyle = color; x.lineWidth = 1.6; x.beginPath(); r.curves.forEach((d, i) => { const px = m.l + d.epsilon * pw, py = h - m.b - d[key] / max * ph; i ? x.lineTo(px, py) : x.moveTo(px, py); }); x.stroke(); }); marker(x, m.l + state.epsilon * pw, m.t, h - m.b); x.fillStyle = "#8291a4"; x.font = "9px Inter"; x.fillText("Betti curves", m.l, 10); x.fillText(String(max), 3, m.t + 3); }
  function drawBarcode(r) { const { x, w, h } = preparePlot("barcodePlot", 136), m = { l: 29, r: 8, t: 17, b: 15 }, pw = w - m.l - m.r; x.fillStyle = "#8291a4"; x.font = "9px Inter"; x.fillText("Longest persistence bars", m.l, 10); function bars(label, data, color, start, count) { x.fillStyle = color; x.fillText(label, 4, start + 4); data.slice().sort((a, b) => b[1] - b[0] - (a[1] - a[0])).slice(0, count).forEach((bar, i) => { const y = start + i * 7; x.strokeStyle = color; x.globalAlpha = 1 - i * .08; x.lineWidth = 2; x.beginPath(); x.moveTo(m.l + bar[0] * pw, y); x.lineTo(m.l + bar[1] * pw, y); x.stroke(); }); x.globalAlpha = 1; } bars("H₀", r.h0, "#72e5ff", 24, 4); bars("H₁", r.h1, "#ff6fcf", 60, 5); if (state.areaFill) bars("H₂", r.h2, "#a4ef9b", 103, 3); marker(x, m.l + state.epsilon * pw, m.t, h - m.b); }
  function marker(x, px, top, bottom) { x.save(); x.strokeStyle = "rgba(255,211,110,.75)"; x.setLineDash([3, 3]); x.beginPath(); x.moveTo(px, top); x.lineTo(px, bottom); x.stroke(); x.restore(); }

  function applyLayout(name) { if (name === "radial" && state.selectedIds.size !== 1) return; state.layout = name; let targets; if (name === "semantic") targets = Model.semanticTargets(graph.nodes, state.clusterMode); else if (name === "hierarchical") targets = Model.hierarchicalTargets(graph.nodes); else if (name === "cluster") targets = Model.clusterTargets(graph.nodes, state.clusterMode); else if (name === "radial") targets = Model.radialTargets(graph, Array.from(state.selectedIds)[0]); else targets = Model.homeTargets(graph.nodes); Model.applyTargets(graph.nodes, targets, false); state.transitioning = true; state.physics = false; $("physicsToggle").textContent = "resume"; $("physicsToggle").classList.remove("active"); }
  function restoreLayout() { state.rx = -.55; state.ry = .62; state.panX = state.panY = state.focusX = state.focusY = state.focusZ = 0; state.targetDist = 760; state.targetZoom = 1; applyLayout("semantic"); $("layoutSelect").value = "semantic"; }
  function stir() { const values=api("/api/graph/stir",{nodes:graph.nodes.map(cleanNode)});values.forEach(v=>Object.assign(graph.nodeMap.get(v.id),v));resumePhysics(); }
  function project(n) { let x = (n.x - state.focusX + state.panX) * state.spread, y = (n.y - state.focusY + state.panY) * state.spread, z = state.mode === "2d" ? 0 : (n.z - state.focusZ) * state.spread; if (state.mode === "3d") { const cy = Math.cos(state.ry), sy = Math.sin(state.ry), x1 = cy * x + sy * z, z1 = -sy * x + cy * z, cx = Math.cos(state.rx), sx = Math.sin(state.rx); x = x1; z = sx * y + cx * z1; y = cx * y - sx * z1; } const perspective = state.mode === "2d" ? state.dist / 760 : state.dist / Math.max(80, state.dist + z + 700), s = perspective * state.zoom; return { x: state.w / 2 + x * s, y: state.h / 2 - y * s, z, s }; }
  function drawEdge(edge, highlighted) { const a = edge.a._p || project(edge.a), b = edge.b._p || project(edge.b), active = !state.tda || edge.filterWeight <= state.epsilon, cycle = state.tda && topologyResult.current.cycleEdgeIds.has(edge.id), merge = state.tda && topologyResult.current.mergeEdgeIds.has(edge.id); ctx.save(); if (state.tda) { ctx.globalAlpha = active ? (cycle ? .92 : highlighted ? .88 : .5) : .035; ctx.strokeStyle = cycle ? "#ff6fcf" : merge ? "#72e5ff" : "#536073"; } else { ctx.globalAlpha = state.selectedIds.size ? (highlighted ? .8 : .08) : .26; ctx.strokeStyle = highlighted ? "#f4ecd3" : colorKey(edge.type); } if (state.search && !(searchMatches.has(edge.a.id) && searchMatches.has(edge.b.id))) ctx.globalAlpha *= .2; ctx.lineWidth = Math.max(.65, (cycle ? 1.8 : highlighted ? 1.25 : .82) * Math.min(a.s, b.s) * state.pixel); if (!active) ctx.setLineDash([2 * state.pixel, 4 * state.pixel]); ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); if (edge.directed && active) { const angle = Math.atan2(b.y - a.y, b.x - a.x), r = 5 * state.pixel; ctx.fillStyle = ctx.strokeStyle; ctx.beginPath(); ctx.moveTo(b.x, b.y); ctx.lineTo(b.x - Math.cos(angle - .42) * r, b.y - Math.sin(angle - .42) * r); ctx.lineTo(b.x - Math.cos(angle + .42) * r, b.y - Math.sin(angle + .42) * r); ctx.closePath(); ctx.fill(); } ctx.restore(); }
  function drawNode(n, highlighted) { const p = n._p, r = radiusFor(n) * Math.max(.38, p.s) * state.pixel, context = !state.selectedIds.size || activeContext.has(n.id); ctx.save(); ctx.globalAlpha = highlighted ? 1 : context ? .9 : .13; if (state.search && !searchMatches.has(n.id)) ctx.globalAlpha *= .18; const color = colorFor(n), glow = ctx.createRadialGradient(p.x, p.y, r * .1, p.x, p.y, r * 2.7); glow.addColorStop(0, "#fff"); glow.addColorStop(.22, color); glow.addColorStop(1, "transparent"); ctx.fillStyle = glow; ctx.beginPath(); ctx.arc(p.x, p.y, r * 2.7, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = color; ctx.beginPath(); ctx.arc(p.x, p.y, r, 0, Math.PI * 2); ctx.fill(); if (state.selectedIds.has(n.id)) { ctx.strokeStyle = "rgba(255,255,255,.86)"; ctx.lineWidth = 1.3 * state.pixel; ctx.beginPath(); ctx.arc(p.x, p.y, r * 1.65, 0, Math.PI * 2); ctx.stroke(); } if (state.tda && topologyResult.componentColorByNode.has(n.id)) { ctx.strokeStyle = topologyResult.componentColorByNode.get(n.id); ctx.lineWidth = 1.2 * state.pixel; ctx.beginPath(); ctx.arc(p.x, p.y, r * 1.95, 0, Math.PI * 2); ctx.stroke(); } ctx.restore(); n._radius = r; }
  function drawFaces() { if (!state.tda || !state.areaFill) return; topologyResult.activeFaces.slice(0, 80).forEach(face => { const points = face.vertices.map(id => graph.nodeMap.get(id)).filter(Boolean).map(n => n._p || project(n)); if (points.length !== 4) return; ctx.save(); ctx.globalCompositeOperation = "screen"; ctx.globalAlpha = .03 + .045 * (1 - face.birth); ctx.fillStyle = "#ff6fcf"; ctx.strokeStyle = "#d26ab1"; ctx.lineWidth = .55 * state.pixel; ctx.beginPath(); ctx.moveTo(points[0].x, points[0].y); points.slice(1).forEach(p => ctx.lineTo(p.x, p.y)); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.restore(); }); }
  function drawLabels(nodes) { if (!state.labels) return; const occupied = [], detail = Math.max(0, Math.min(1, Math.log2(Math.max(1, state.zoom)) / 5)), candidates = nodes.map(n => ({ n, forced: state.selectedIds.has(n.id) || n === state.hovered || (state.search && searchMatches.has(n.id)), score: n.degree * 9 + n.rank * 500 + n._p.s * 15 })).sort((a, b) => Number(b.forced) - Number(a.forced) || b.score - a.score), limit = Math.round(nodes.length * (.06 + state.labelDensity * .5 + detail * .45)); candidates.forEach((item, index) => { if (!item.forced && index > limit) return; const n = item.n, p = n._p, size = (item.forced ? 10.5 : 9) * state.pixel; ctx.font = `${size}px Inter`; const width = ctx.measureText(n.label).width + 8 * state.pixel, height = 15 * state.pixel, box = { x: p.x - width / 2, y: p.y - n._radius - height - 3, w: width, h: height }; if (!item.forced && occupied.some(b => b.x < box.x + box.w && b.x + b.w > box.x && b.y < box.y + box.h && b.y + b.h > box.y)) return; occupied.push(box); ctx.save(); ctx.globalAlpha = item.forced ? 1 : .84; if (item.forced) { ctx.fillStyle = "rgba(3,8,13,.78)"; ctx.beginPath(); ctx.roundRect ? ctx.roundRect(box.x, box.y, box.w, box.h, 4 * state.pixel) : ctx.rect(box.x, box.y, box.w, box.h); ctx.fill(); } ctx.fillStyle = item.forced ? "#fff" : "#dce6f1"; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(n.label, p.x, box.y + height / 2); ctx.restore(); }); const level = detail < .2 ? "overview" : detail < .5 ? "structure" : detail < .78 ? "detail" : "close"; $("zoomBadge").textContent = `label detail · ${level} · ${Math.round(state.zoom * 100)}%`; }
  function drawOrientation() { const c = orientation.width / 2; octx.clearRect(0, 0, orientation.width, orientation.height); octx.save(); octx.translate(c, c); [["x", "#7aa2f7", [1, 0, 0]], ["y", "#a9d18e", [0, 1, 0]], ["z", "#c792ea", [0, 0, 1]]].forEach(([label, color, v]) => { let [x, y, z] = v; const cy = Math.cos(state.ry), sy = Math.sin(state.ry), x1 = cy * x + sy * z, z1 = -sy * x + cy * z, cx = Math.cos(state.rx), sx = Math.sin(state.rx), y2 = cx * y - sx * z1; octx.strokeStyle = octx.fillStyle = color; octx.lineWidth = 2 * state.pixel; octx.beginPath(); octx.moveTo(0, 0); octx.lineTo(x1 * 28 * state.pixel, -y2 * 28 * state.pixel); octx.stroke(); octx.font = `${9 * state.pixel}px Inter`; octx.fillText(label, x1 * 33 * state.pixel, -y2 * 33 * state.pixel); }); octx.restore(); }
  function animate() { state.dist += (state.targetDist - state.dist) * .12; state.zoom *= Math.pow(state.targetZoom / state.zoom, .18); if (state.selectedIds.size === 1 && state.selected) { state.targetFocusX = state.selected.x; state.targetFocusY = state.selected.y; state.targetFocusZ = state.selected.z; } else state.targetFocusX = state.targetFocusY = state.targetFocusZ = 0; state.focusX += (state.targetFocusX - state.focusX) * .09; state.focusY += (state.targetFocusY - state.focusY) * .09; state.focusZ += (state.targetFocusZ - state.focusZ) * .09; if (state.autoRotate && state.mode === "3d" && !state.drag) state.ry += .0015; if (state.transitioning) state.transitioning = Model.transitionStep(graph.nodes, .075); else if (state.physics) Model.forceStep(graph, { relations: state.relationGravity, extra: state.force.extra, anchor: state.force.anchor, repulsion: state.force.repulsion, collision: state.force.collision, anchors }); ctx.clearRect(0, 0, state.w, state.h); const nodes = graph.nodes.filter(visible); nodes.forEach(n => n._p = project(n)); drawFaces(); eligibleEdges().forEach(e => { const highlighted = !state.selectedIds.size || (activeContext.has(e.a.id) && activeContext.has(e.b.id)); drawEdge(e, highlighted); }); nodes.sort((a, b) => a._p.z - b._p.z).forEach(n => drawNode(n, state.selectedIds.has(n.id) || n === state.hovered)); drawLabels(nodes); drawOrientation(); requestAnimationFrame(animate); }
  function hit(x, y) { return graph.nodes.filter(visible).map(n => ({ n, d: (n._p.x - x) ** 2 + (n._p.y - y) ** 2 })).filter(x => x.d < (x.n._radius * 2.1) ** 2).sort((a, b) => a.d - b.d)[0]?.n || null; }
  function resize() { state.pixel = devicePixelRatio || 1; state.w = canvas.width = canvas.clientWidth * state.pixel; state.h = canvas.height = canvas.clientHeight * state.pixel; orientation.width = 104 * state.pixel; orientation.height = 104 * state.pixel; if (topologyResult) drawTDAPlots(); }

  async function install() { window.addEventListener("resize", resize); resize(); const resolved = await resolveSnapshot(); initialize(resolved.raw, resolved.meta);
    $("weightField").onchange=()=>{prepareWeights();recomputeTDA();};
    try{const canonical=await (await fetch('/api/csv/schema')).json();document.querySelectorAll('[data-schema-help]').forEach(el=>el.textContent=canonical.help);}catch(_){}
    $("openML").onclick=async()=>{await saveBrowserSnapshot(snapshot(),meta);if(parent===window){sessionStorage.setItem('ml-use-csv','1');location.href='/';}else parent.postMessage({type:'open-csv-in-ml'},location.origin);};
    $("chooseCSV").onclick = () => $("csvInput").click(); $("csvInput").onchange = e => inspectFiles(e.target.files); const drop = $("importDrop"); drop.onclick = () => $("csvInput").click(); drop.onkeydown = e => { if (e.key === "Enter" || e.key === " ") $("csvInput").click(); }; ["dragenter", "dragover"].forEach(type => drop.addEventListener(type, e => { e.preventDefault(); drop.classList.add("over"); })); ["dragleave", "drop"].forEach(type => drop.addEventListener(type, e => { e.preventDefault(); drop.classList.remove("over"); })); drop.addEventListener("drop", e => inspectFiles(e.dataTransfer.files));
    $("exportGraph").onclick = async () => {
      const r=await fetch('/api/graph/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot())});
      if(!r.ok){$("importStatus").textContent="Export failed; graph unchanged.";return;}
      download("ml-knowledge-graph.json",await r.text());
    }; const restore = async () => { if (!confirm("Restore the bundled science snapshot? The imported browser snapshot will be removed.")) return; await deleteDatabaseSnapshot(); localStorage.removeItem(STORAGE_KEY); localStorage.removeItem(META_KEY); location.reload(); }; $("restoreSnapshot").onclick = $("loadSample").onclick = restore;
    $("layoutSelect").onchange = e => applyLayout(e.target.value); $("autoRotate").onclick = e => { state.autoRotate = !state.autoRotate; e.currentTarget.classList.toggle("active", state.autoRotate); }; $("captureGraph").onclick = () => { const link = document.createElement("a"); link.download = "universal-constellation.png"; link.href = canvas.toDataURL("image/png"); link.click(); }; $("toggleSettings").onclick = () => { if (innerWidth <= 760) { $("left").classList.toggle("mobile-open"); return; } $("left").classList.toggle("collapsed"); $("app").classList.toggle("settings-collapsed", $("left").classList.contains("collapsed")); };
    $("showSources").onchange = e => { state.showSources = e.target.checked; refreshContext(); }; $("showOutcomes").onchange = e => { state.showOutcomes = e.target.checked; refreshContext(); }; $("viewMode").onchange = e => { state.mode = e.target.value; if (state.mode === "2d") state.rx = state.ry = 0; };
    $("colorMode").onchange = e => { state.colorMode = e.target.value; buildLegend(); }; $("sizeMode").onchange = e => state.sizeMode = e.target.value; $("clusterMode").onchange = e => { state.clusterMode = e.target.value; buildAnchors(); if (["semantic", "cluster"].includes(state.layout)) applyLayout(state.layout); }; $("weightMode").onchange = e => { state.weightMode = e.target.value; prepareWeights(); recomputeTDA(); };
    $("labels").onclick = e => { state.labels = !state.labels; e.target.textContent = state.labels ? "auto labels" : "labels off"; e.target.classList.toggle("active", state.labels); }; $("local").onclick = e => { state.local = !state.local; e.target.classList.toggle("active", state.local); changedVisibility(); }; $("home").onclick = () => { selectNode(null, false); state.rx = -.55; state.ry = .62; state.panX = state.panY = 0; state.targetDist = 760; state.targetZoom = 1; applyLayout("force"); $("layoutSelect").value = "force"; resumePhysics(); }; $("fit").onclick = () => state.targetZoom = .82; $("reset").onclick = () => { state.spread = 1; $("spread").value = 100; $("spreadValue").value = "100%"; restoreLayout(); }; $("spread").oninput = e => { state.spread = e.target.value / 100; $("spreadValue").value = `${e.target.value}%`; };
    $("physicsToggle").onclick = e => { state.physics = !state.physics; Model.cancelPhysics(); state.transitioning = false; e.target.textContent = state.physics ? "pause" : "resume"; e.target.classList.toggle("active", state.physics); }; $("stir").onclick = stir; $("restoreLayout").onclick = restoreLayout; [["extraGravity", "extra"], ["anchorGravity", "anchor"], ["repulsionGravity", "repulsion"], ["collisionGravity", "collision"]].forEach(([id, key]) => $(id).oninput = e => { state.force[key] = e.target.value / 100; e.target.nextElementSibling.value = e.target.value; resumePhysics(); }); $("labelDensity").oninput = e => { state.labelDensity = e.target.value / 100; e.target.nextElementSibling.value = e.target.value; };
    $("tdaMode").onclick = e => { state.tda = !state.tda; e.target.textContent = state.tda ? "disable" : "enable"; e.target.classList.toggle("active", state.tda); recomputeTDA(); }; $("areaMode").onclick = e => { state.areaFill = !state.areaFill; if (state.areaFill) { state.tda = true; $("tdaMode").textContent = "disable"; $("tdaMode").classList.add("active"); } e.target.textContent = state.areaFill ? "areas filled" : "fill areas"; e.target.classList.toggle("active", state.areaFill); recomputeTDA(); }; $("epsilon").oninput = e => { state.epsilon = e.target.value / 100; $("epsilonValue").value = state.epsilon.toFixed(2); recomputeTDA(); };
    let timer; $("search").oninput = e => { clearTimeout(timer); timer = setTimeout(() => { const term = e.target.value.trim().toLowerCase(); state.search = term; searchMatches = new Set(graph.nodes.filter(n => !term || searchable(n).includes(term)).map(n => n.id)); if (term && searchMatches.size === 1) selectNode(graph.nodeMap.get(Array.from(searchMatches)[0]), false); }, 120); }; $("search").onkeydown = e => { if (e.key === "Escape") { e.target.value = ""; state.search = ""; searchMatches = new Set(graph.nodes.map(n => n.id)); } };
    canvas.oncontextmenu = e => e.preventDefault(); canvas.onmousedown = e => { const x = e.offsetX * state.pixel, y = e.offsetY * state.pixel, node = hit(x, y); if(node)node._dragging=true; state.drag = node && e.button === 0 ? { type: "node", node } : { type: e.button === 2 ? "pan" : "orbit" }; state.lastX = x; state.lastY = y; state.moved = false; canvas.style.cursor = "grabbing"; }; window.onmouseup = () => { if(state.drag?.node)state.drag.node._dragging=false; if (state.drag?.type === "node" && state.moved) state.suppressClick = true; state.drag = null; canvas.style.cursor = state.hovered ? "pointer" : "grab"; }; window.onmousemove = e => { const rect = canvas.getBoundingClientRect(), x = (e.clientX - rect.left) * state.pixel, y = (e.clientY - rect.top) * state.pixel, dx = x - state.lastX, dy = y - state.lastY; if (state.drag) { state.moved ||= Math.abs(dx) + Math.abs(dy) > 1; if (state.drag.type === "orbit" && state.mode === "3d") { state.ry += dx * .004; state.rx = Math.max(-1.35, Math.min(1.35, state.rx + dy * .004)); } else if (state.drag.type === "pan" || state.mode === "2d" && state.drag.type === "orbit") { state.panX += dx / state.pixel; state.panY -= dy / state.pixel; } else if (state.drag.type === "node") { const n = state.drag.node, inv = 1 / Math.max(.2, n._p.s); n.x += dx / state.pixel * inv; n.y -= dy / state.pixel * inv; n.vx = n.vy = n.vz = 0; } state.lastX = x; state.lastY = y; return; } const node = hit(x, y); state.hovered = node; if (node) { $("explorerTooltip").textContent = node.label; $("explorerTooltip").style.left = `${e.clientX - rect.left + 18}px`; $("explorerTooltip").style.top = `${e.clientY - rect.top + 14}px`; $("explorerTooltip").classList.add("show"); canvas.style.cursor = "pointer"; } else { $("explorerTooltip").classList.remove("show"); canvas.style.cursor = "grab"; } }; canvas.onclick = e => { if (state.suppressClick) { state.suppressClick = false; return; } selectNode(hit(e.offsetX * state.pixel, e.offsetY * state.pixel), e.shiftKey); }; canvas.ondblclick = e => { const node = hit(e.offsetX * state.pixel, e.offsetY * state.pixel); if (!node) return; if ((e.ctrlKey || e.metaKey || e.altKey) && safeURL(node.url)) { window.open(safeURL(node.url), "_blank", "noopener"); return; } selectNode(node, false); $("layoutSelect").value = "radial"; applyLayout("radial"); }; canvas.onwheel = e => { e.preventDefault(); const delta = e.deltaMode === 1 ? e.deltaY * 16 : e.deltaMode === 2 ? e.deltaY * Math.max(1, state.h / state.pixel) : e.deltaY; state.targetZoom = Math.max(.02, Math.min(10000, state.targetZoom * Math.exp(-delta * .0015))); };
    requestAnimationFrame(animate);
  }
  install();
})();
